/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#include <tmwtypes.h>

int call_qpoases(	double nV, double nC,
                    double* const H, const double* const g, double* const A, const double* const lb, const double* const ub, const double* const lbA, const double* const ubA,
					double* x, double* fval, double* exitflag, double* iter, double* lambda
					);
