/*
 *    This file was auto-generated by ACADO Toolkit.
 *
 *    ACADO Toolkit -- A Toolkit for Automatic Control and Dynamic Optimization.
 *    Copyright (C) 2008-2011 by Boris Houska, Hans Joachim Ferreau et al., K.U.Leuven.
 *    Developed within the Optimization in Engineering Center (OPTEC) under
 *    supervision of Moritz Diehl. All rights reserved.
 *
 */


#define __SINGLE_OBJECT__
#define __XPCTARGET__
#define inline 


#include <stdio.h>
#include <math.h>

/*typedef double real_t;*/

#include "qpoases3/include/qpOASES.h"
#include "call_qpoases.h"



int call_qpoases(	double nV, double nC,
                    double* const H, const double* const g, double* const A, const double* const lb, const double* const ub, const double* const lbA, const double* const ubA,
					double* x, double* fval, double* exitflag, double* iter, double* lambda
					)
{
/*   int nWSR = QPOASES_NWSRMAX; */
    int nWSR = 100;

  returnValue retVal;

  Options options;
  QProblem qp;
  
  QProblemCON( &qp,(int)nV,(int)nC,HST_POSDEF );
  Options_setToMPC( &options );
  QProblem_setOptions( &qp,options );
  
  retVal = QProblem_init( &qp,H,g,A,lb,ub,lbA,ubA, &nWSR,0 );

  QProblem_getPrimalSolution( &qp,x );
  *fval = QProblem_getObjVal( &qp );
  *exitflag = (double)(qpOASES_getSimpleStatus( retVal,0 ));
  *iter = (double)(nWSR);
  QProblem_getDualSolution( &qp,lambda );

  return retVal;
}
